# # 抖音推送列表
# douyin:
#   -
#     # 抖音用户（可不填，执行推送时会自动填上）
#     sec_uid: 
#     # 抖音号（必填）
#     short_id: 
#     # 推送群号和机器人账号，多个则使用逗号隔开（必填，例子：[12345678:87654321, 11451419:88888888]，群号就是11451419，机器人账号就是88888888）
#     group_id:
#       - 1145141919810:8888888888
#     # 这个博主的名字信息（可不填，执行推送时会自动填上）
#     remark: 
#     # 推送类型（可选，默认为 [post]）
#     # post: 作品列表
#     # favorite: 喜欢列表
#     # recommend: 推荐列表
#     # live: 直播
#     # 可以同时推送多种类型，例如：[post, favorite, live]
#     pushTypes:
#       - post

# # B站推送列表
# bilibili:
#   -
#     # B站用户（必填）
#     host_mid: 
#     # 推送群号和机器人账号，多个则使用逗号隔开（必填，例子：[12345678:87654321, 11451419:88888888]，群号就是11451419，机器人账号就是88888888）
#     group_id:
#       - 1145141919810:8888888888
#     # 这个UP主的名字信息（可不填，执行推送时会自动填上）
#     remark: 

# 抖音推送列表
douyin: []

# B站推送列表
bilibili: []