blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/ikenxuan/karin-plugin-kkk/discussions
    about: æœ‰é—®é¢˜æƒ³è®¨è®ºï¼Ÿæ¬¢è¿åˆ°è®¨è®ºåŒºäº¤æµ
  - name: ğŸ“– æ–‡æ¡£
    url: https://karin-plugin-kkk-docs.vercel.app
    about: æŸ¥çœ‹é¡¹ç›®æ–‡æ¡£å’Œä½¿ç”¨è¯´æ˜
