# 视频解析工具总开关，修改后重启生效
videoTool: true

# 自定义优先级，「默认解析」关闭后才会生效。修改后重启生效
priority: 800

# 缓存删除，非必要不修改！
removeCache: true

# 渲染精度，可选值50~200，建议100。设置高精度会提高图片的精细度，过高可能会影响渲染与发送速度
renderScale: 100

# 放出API服务（本地部署一个抖音、B站和快手的api服务）
APIServer: false

# API服务端口
APIServerPort: 4567

# API 服务是否挂载到 Karin 上，开启后监听端口为 Karin 的 http 端口，修改后需重启
APIServerMount: true

# 渲染评论图和推送图的主题色，0为自动（06:00-18:00为浅色，18:00-06:00为深色），1为浅色，2为深色
Theme: 0

# 渲染的图片是否移除底部水印
RemoveWatermark: false

# 渲染图片的等待时间，单位：秒。传递 0 可禁用等待（Linux系统必须大于0）
RenderWaitTime: 60

# 表情回应
EmojiReply: true

# 表情 ID，详情查看：https://github.com/NapNeko/NapCatQQ/blob/main/src/core/external/face_config.json
EmojiReplyID: 128064

# web解析页面是否启用鉴权
webAuth: true
